### PR TITLE
alphabetize keys

### PR DESCRIPTION
**Pull request by charlierudolph**
@swang

### CODE REVIEW

**Comment by AsaAyers** [comment]
IMO This seems like an overly strict rule that makes more sense as a 3rd party rule than something to ship in the core. We already detect duplicate keys, so this only seems useful for locating keys in very very large classes, which is a different problem.

**Comment by swang** [comment]
Yeah I think I have to agree with @AsaAyers. I'm not actually sure this is commonly done where we would want to add a rule to enforce it.

**Comment by charlierudolph** [comment]
Just wanted to add some things here

There are plenty of strict rules in here that are ignored by default. Thus I don't think anything in here can really be "overly restrictive" as it can always be turned off. 

I understand you don't want to accept just every rule that someone comes up, and want it to be something that makes sense and will likely be used. Granted I also got `braces_padding` merged in and I personally don't see how thats different. Just because its not something people do now, doesn't mean its a bad thing. Do you not find it useful when keys/methods are in alphabetical order?

I'm fine adding configuration to this such as whether or not classes are linted or the minimum/maximum number of keys. Personally I think very, very large classes probably means you need to refactor the logic into separate classes. (There is another potential for a coffeelint rule which is how maximum methods in a class).

Either way this is now a [rule](https://github.com/charlierudolph/coffeelint-alphabetize-keys) for it

**Comment by AsaAyers** [comment]
Some rules are core because there wasn't a way to have 3rd party rules for a long time, and others I accepted just because it seemed convenient.

When we launch 2.0 and break compatibility, I think we should strip stylistic rules and only keep the ones that actually prevent errors or are really bad practice with CoffeeScript.

**Comment by charlierudolph** [comment]
That sounds good. Would be cool to start a coffeescript version of [jscs](https://github.com/jscs-dev/node-jscs)

**Comment by AsaAyers** [comment]
CoffeeScript can already lint CJSX. https://github.com/clutchski/coffeelint/blob/master/doc/user.md#how-do-i-use-jsx-reactjs

I highly recommend if you're considering using JSX like syntax, just move to Babel and use ES6 and abandon CoffeeScript.

**Comment by charlierudolph** [comment]
I'm not talking about JSX. Just a repo where all the style rules could go.

**Comment by swang** [comment]
It's probably the right thing to separate actual problematic code rules from stylistic rules, but I'm not sure I want to do that with CoffeeLint. I would consider publishing them as 3rd party rules to get them out of the main core/codebase though if that's what you're referring to. I actually kinda like that: having a separate organization that has these 3rd party rules. But otherwise I don't think there are enough resources to split this project out into 2 separate libraries like what jshint has done with jscs. Also I find it annoying having to maintain two dotfiles for jshint and jscs.

As for why braces_padding was accepted and alphabetize_keys wasn't: One factor was that we already included padding/spacing rules for other things like parens and brackets so that was more in line with what was already in coffeelint. But secondly, I just don't see that many people worried about this specific thing stylistically. Obviously this is entirely subjective, because at the very least there is 1 person who wants that rule, but I just see a whole bunch of gotchas in terms of what people want. "I only want it for multi-lined objects, I only want it to work with only Y keys, oh I don't want it sorted alphabetically, I want it sorted by length of the key."

That last part is one of the bigger issues. Merging it means that _I_ have to help maintain it since it's part of CoffeeLint, meaning people will file issues here vs. with you. And I don't really know how long you're going to help maintain it. Let's say we do merge it in, then maybe in the future you decide you don't care about ordering keys. Now whose problem is it to maintain it? At least if it is a third-party rule, you will at least bear some responsibility in either deciding "nope I don't want to maintain it anymore" or, "OK I will add this new flag even though I won't ever use it."

It is less burdensome to add this rule at a later time, rather than immediately merge it into this codebase and having people get mad at us for removing it later if we decide it was problematic or not really aligned with the rest of the lint rules.

I hope you don't view this as a judgment of your stylistic preferences. I just don't feel it's really necessary, and the maintenance costs to keep it vs what I feel it's usage will be just don't add up. But at the very least it can still be installed for those who want to use it.

**Comment by charlierudolph** [comment]
Thanks for the reply @swang.

Totally understand the hardships of maintainability and the edge cases that may come up. I just don't think I'll ever see those edge cases thought, as I think its far less likely someone will use my rule when its its own module in the far reaches of github.

**Pull request closed without merging**
