### PR TITLE
no unused variables

### PR DESCRIPTION
**Pull request by charlierudolph**
If I raise the default level to warning or error then I need to update a lot of other tests. 
I'd like to do that in a follow up pull request

### CODE REVIEW

**Comment by AsaAyers** [comment]
I've actually been working on adding a new linter type for handling all kinds of scope rules. It's the [scope-linter](https://github.com/clutchski/coffeelint/compare/scope-linter) branch. The rules are in place and work, but I haven't been able to get [CoffeeScope](https://github.com/AsaAyers/coffeescope) fully functional yet.

Would you be interested in helping out with CoffeeScope? Once I have CoffeeScope fully working I do intend to make the `undefined_variables` and `unused_variables` warn by default.

**Comment by charlierudolph** [comment]
Cool. I like the idea of a ScopeLinter. Another rule I want to add is `no_variable_shadowing`.
What help do you need on CoffeeScope?

**Comment by AsaAyers** [comment]
Since variable creation is implicit there are just a ton of different ways that variables get created or used. I have a bunch of failing tests in the repo, but it often seems like when I fix one thing another breaks.

If we can get CoffeeScope working where it really knows every variable in every scope and where it's been used `no_variable_shadowing` should be fairly straight forward to implement. I also want to add [`no_use_before_define`](http://eslint.org/docs/rules/no-use-before-define)

**Comment by AsaAyers** [comment]
I disabled the failing tests in CoffeeScope to reduce the noise as I turn them on and fix them one at a time. I also added a small README.

I also use gitter, if you'd like to chat you can message me directly or we can use https://gitter.im/AsaAyers/coffeescope. Now I'm going to close this issue and we can move further discussion to gitter or issues in CoffeeScope.

**Pull request closed without merging**
