### PR TITLE
Allow private camel case classes

### LINKED ISSUE #422: _ prefix for UpperCamelCased classes should not be an error
When enabled UpperCamelCased class names having a class name prefixed with `_` (for private names) should not be an error.

### PR DESCRIPTION
**Pull request by mitar**
Fixes #422.

### CODE REVIEW

**Comment by AsaAyers** [comment]
Since turning strict mode on would have no impact on anyone already running this rule, I don't think we need the flag. It isn't going to suddenly start telling people to go change things when they upgrade. What do you think?

**Comment by mitar** [comment]
So I should just modify the regex? Fine by me.

**Comment by mitar** [comment]
Updated.

**Comment by AsaAyers** [comment]
Thanks

**Pull request merged**
