### PR TITLE
Update to CoffeeScript 1.9.1

### PR DESCRIPTION
**Pull request by swang**
# This shouldn't be merged yet as-is since package.json is pointing to jashkenas/coffeescript and not the npm version of coffeescript

This PR is for people to look over and test out so it can be released once CoffeeScript updates past 1.9.0 I also updated browserify/coffeeify to get them running again but since I don't use that functionality in coffeelint someone else will have to verify that it builds out correctly for their use-cases.

------------------------------------------------------------------------

The new lexer was merged from PR made in jashkenas/coffeescript#3770

Also closes #372

no_unnecessary_double_quotes

- Removed Block RegExp Fix that was originally patched in PR #340.
  Thanks to the new PR, this is no longer needed
- Shortened function name `containsSingleQuote` to `hasSingleQuote`
- Changed how we detect if we're inside an interpolated string to be
  more like the way we handle interpolation in space_operators

no_trailing_semicolons rule

- Due to the new way tokens are generated, we now check for 'STRING_END'
  token rather than a 'CALL_END' token

space_operators

- Removed old code that assumed an interpolated string always begins
  with empty quotes. Due to new changes in CoffeeScript lexer, we can
  now use 'STRING_START' to determine the beginning of an interpolated
  string
- Renamed lintParens, lintCall to trackParens, trackCall respectively

### CODE REVIEW

**Comment by AsaAyers** [comment]
Thanks for your work on this. Your work is consistently excellent, so I asked clutchski to give you commit access. :trophy: Even though i have commit access I'll usually open a PR just because it notifies anyone monitoring the project and gives a place to discuss things if anyone else is interested.

**Comment by swang** [comment]
:+1: thanks!

**Comment by alubbe** [comment]
1.9.1 is out, so let's get this show on the road :)

**Comment by swang** [comment]
@AsaAyers can you look over then make a new npm release?

**Comment by AsaAyers** [comment]
:+1:

**Pull request merged**
