### PR TITLE
Addressing default_parameters

### PR DESCRIPTION
**Pull request by mitar**
See #419.

I added tests. But I have no idea how to implement this.

### CODE REVIEW

**Comment by mitar** [comment]
Or at least not without using AST.

**Comment by AsaAyers** [comment]
I'm not sure yet either. I'll try to get back to this some time this week

**Comment by mitar** [comment]
Implemented `default_parameters` option. See #419.

**Comment by aseemk** [comment]
Nice work @mitar!

Q: is `foo = ({a, b, c}={}) ->` supported? We often use that as a shorthand for naming options hashes just to destructure them right after.

**Comment by mitar** [comment]
There is `foo = ({bar}={bar: 42}) ->` test case. I think this is close enough, no?

**Comment by aseemk** [comment]
Cool, I wasn't sure if that exercised the same code path. If it does, great. :+1:

**Comment by mitar** [comment]
The implementation is very simple. If there is `=` inside function parameters (`(` and `)`) it should not contain spaces. So it does not catch things like: `foo = (a=(b='c')) ->`. It will allow it, despite second `=` being an operator.

**Comment by AsaAyers** [comment]
Do you still want to get this merged? I'm going back through older issues and I see this has conflicts now :(

**Comment by mitar** [comment]
Yes, this is important because it is giving false positives on default arguments otherwise.

**Comment by mitar** [comment]
I updated the branch. Let's see if tests pass.

**Comment by swang** [comment]
Two nits:
1. Please squash the two commits together
2. Please use camel case/pascal case rather than snake case for variables in the code, even if the referenced JSON is snake_case.

Like almost all the other optional parameters in coffeelint rules, "default_parameters" is vague. Do I set it to true or false to make it ignore default parameters? IMO it should be clear without having to refer to comments inside of the rule file. I ran into the same problem today working on "no_implicit_braces" with the 'strict' parameter. First off, what does "strict" even mean? Then you have to dig into the codebase (or the original PR/issue) to figure it out.

So I guess before it merges, I would prefer a clearer name (ignore_default_parameters maybe?)

**Comment by UziTech** [comment]
Further development on coffeelint will be on [coffeelint/coffeelint](https://github.com/coffeelint/coffeelint) and will be released as [@coffeelint/cli](https://www.npmjs.com/package/@coffeelint/cli).

This PR will be tracked at https://github.com/coffeelint/coffeelint/pull/16

**Pull request closed without merging**
