### PR TITLE
Support for tab indented literate files added

### PR DESCRIPTION
**Pull request by KrysKruk**
This PR adds support for trailing tab whitespace in literate files.
See #557 for more.

### CODE REVIEW

**Comment by swang** [comment]
Thanks. It does seem like Literate CoffeeScript should indeed support 4 spaces or 1 tab. However I just tried it out on this test case.

```coffeescript
This is a function that returns 'hello'
	() ->
		"hello"

Wow that was easy!
```

And it produces
```javascript
(function() {


}).call(this);
````

Is this working on your end? I'm running node 4.0.0 (tried node 0.12.0 as well) running the latest coffeescript.

I looked around CoffeeScript's source code and it seems like a change made 3 years ago caused this so you may have to file an issue with them to get it fixed. After that I can merge in this code.

https://github.com/jashkenas/coffeescript/commit/52ca531b7c9f1fc6f3ba76d2ac2527c41f9ece68

**Comment by KrysKruk** [comment]
Hi @swang Thank you for feedback!

I think your test case works well, it should produce an empty function, because Markdown requires one extra empty line before indented code. It's easy to test on GitHub comments. If I add one blank line before the code, everything works well. What do you think? Should coffeelint support this test case?

**Comment by swang** [comment]
Ah I did not know that you needed to add an additional line since it doesn't seem to be mentioned in any of the docs. I assumed the indentation was enough.

**Comment by KrysKruk** [comment]
Thank's for merging this into the main branch.
Do you know, when new version will be published in NPM?

**Comment by swang** [comment]
I just released 1.15.1 that includes your PR.

**Comment by KrysKruk** [comment]
@swang Thank you again for quick response. Have a nice day!

**Pull request merged**
