### PR TITLE
updated coffee to 1.9

### PR DESCRIPTION
**Pull request by alubbe**

### CODE REVIEW

**Comment by alubbe** [comment]
Meh - why does this break? On my windows machine, I get about 11-13 breaking tests no matter whether I choose coffee 1.7.1, 1.8.0 or 1.9.0

**Comment by alubbe** [comment]
Now I have tested this more extensively on Ubuntu, where 1.8 works fine, but 1.9 introduces issues related to indentation - I am afraid I do not yet have a good enough grasp of this library's inner workings to understand why. Could someone help me take a look?

**Comment by bausmeier** [comment]
:+1:

**Comment by alubbe** [comment]
@clutchski any pointers?

**Comment by bausmeier** [comment]
This seems to be a bug in coffeescript introduced in 1.9. See https://github.com/jashkenas/coffeescript/issues/3822.

**Comment by AsaAyers** [comment]
@alubbe I'm the current maintainer of CoffeeLint. I haven't had much time to look at this, the upgrade just hasn't been a big priority for me. As far as I can tell you only need 1.9 if you're using generators.

I see that CoffeeScript issue was opened by @swang, one of the [top CoffeeLint contributors](https://github.com/clutchski/coffeelint/graphs/contributors?from=2013-12-25&to=2015-02-03&type=c). I think we'll probably wait for an upstream fix, hopefully in 1.9.1.

**Comment by swang** [comment]
I'm slowly working through the problems I've seen. The above mentioned issue has been fixed, however some code handling for operator spacing is not yet fixed. I've submitted a PR (merged) jashkenas/coffeescript#3830 and also submitted another issue with extra/duplicate string interpolation tags jashkenas/coffeescript#3831. Once these issues get fixed I'll put another run-through of the tests. These should be the last issues before we can implement linting for 1.9.x

**Comment by alubbe** [comment]
thanks for your effort @swang!

**Comment by lydell** [comment]
You might be interested in that since jashkenas/coffeescript#3840 strings and regexes with interpolations produce different tokens than before:

- Strings: Not wrapped in `(` and `)` anymore, but `STRING_START`and `STRING_END`. No more `.stringEnd` property.
- Regexes: Now wrapped in `REGEX_START` and `REGEX_END`. No more `.regexEnd` property.

**Comment by swang** [comment]
Ah thanks for the heads up! I actually had a rule fix based off stringEnd. Will take a look at it later tonight.

**Pull request closed without merging**
