### PR TITLE
A rule to require an empty line at the end of the file

### LINKED ISSUE #431: A rule to require an empty line at the end of the file
Feature request.

So just an empty line character, so that it is a proper text file by some definitions of a text tile.

### PR DESCRIPTION
**Pull request by mitar**
Fixes #431.

### CODE REVIEW

**Comment by AsaAyers** [comment]
I think this would be more useful if it verifies there is exactly 1 empty line at the end of the file. CoffeeLint will construct a new instance of your class for each file, so you can do things like store a count of `@consecutiveBlankLines` and return an error if it isn't `1` when the last line processes.

**Comment by AsaAyers** [comment]
That strategy could also work for #430 , thought I don't think I'd merge them into one rule.

**Comment by mitar** [comment]
I looked at [eol-last documentation](http://eslint.org/docs/rules/eol-last). They do the same as I am doing now, I think. The behavior you are describing was removed. Or am I misreading the documentation?

**Comment by mitar** [comment]
But it is true that at least I am OK with an empty line between code segments, but not an empty line by itself on the end of the file). So i would be OK adding this to this rule if you think it is OK.

**Comment by AsaAyers** [comment]
ok. I've never used that rule so I wasn't aware. I just know that Atom trims all the extra lines I leave at the end for me. Which can be annoying on code I'm only opening for reference but is nice for new files.

I think this is a case where it makes sense to follow the lead of eslint. I'll merge this as is and the multiple last lines can be handled by another rule. :+1: 

Thanks for your work this weekend. It's hard to find people who care enough to contribute.

**Comment by mitar** [comment]
There is a package for this: https://github.com/Dreamscapes/coffeelint-newline-at-eof

**Pull request merged**
