### PR TITLE
pedantic, semantic alteration.

### PR DESCRIPTION
**Pull request by 7yl4r**
lowerCamelCase vs UpperCamelCase, who really cares? Apparently I do. :innocent:

### CODE REVIEW

**Comment by AsaAyers** [comment]
Please drop PascalCased from the message, it isn't necessary as the message itself contains an example. When using CoffeeLint through editor plugins you often have limited room for messages, so I'd prefer to avoid having extra stuff. If you really want to mention PascalCased it can go in the description.

Please also fix the tests.

**Comment by 7yl4r** [comment]
disregard. I forgot to fix the tests. Will resubmit when fixed, sorry.

**Comment by 7yl4r** [comment]
sorry about the commit spam due to editing via github

**Comment by AsaAyers** [comment]
Thanks, looks fine to me.

**Pull request merged**
