### PR TITLE
Track the number of open strings for nested string interpolation

### PR DESCRIPTION
**Pull request by robhor**
Addresses bugs with nested string interpolation (#447, #441, #368).

Nested string interpolation produces nested `STRING_START` and `STRING_END` tokens,
for example `"#{"#{a}"}bc"` gets tokenized to
```
[STRING_START (] [( (] [STRING_START (] [STRING ""] [+ +] [( (] [IDENTIFIER a] [) )] [STRING_END )] [) )] [+ +] [STRING "bc"] [STRING_END )]
```

Setting `@isInterpolation` to `false` when the first `STRING_END` token is encountered is too early, as only the inner string interpolation has ended at this point.

To correct this, this PR tracks the number of started but not yet ended strings.
As long as there are unmatched `STRING_START` tokens we are still inside of an interpolation.

### CODE REVIEW

**Comment by flowlo** [comment]
:+1:

**Comment by AsaAyers** [comment]
Before I consider merging, can you show me any example of good (clear, easy to read) code that needs nested interpolation? This still seems like either a contrived problem, or a method of justifying bad code.

**Comment by robhor** [comment]
I consider showing incorrect and misleading warnings a bug, whether or not nested string interpolation is considered good style.
If you like I'll add a rule that warns about nested string interpolation.

**Comment by AsaAyers** [comment]
:+1: I agree, and that's a good idea. Please set it to warn by default.

**Comment by robhor** [comment]
@AsaAyers Added the rule `no_nested_string_interpolation`!

**Comment by AsaAyers** [comment]
Thanks :)

**Pull request merged**
