### PR TITLE
Make tests pass with latest master of CoffeeScript

### PR DESCRIPTION
**Pull request by lydell**
Tested with jashkenas/coffeescript commit d7e752b.

They also still pass with latest stable CoffeeScript (1.10.0).

1. Run `npm test` as usual to verify that it works with CoffeeScript 0.10.0.
2. Install latest master of CoffeeScript and run `npm test`.

NOTE: The most common change in this PR is adding checks for the new 'PROPERTY' around code that looks for the 'IDENTIFIER' token. There are more occurances of 'IDENTIFIER' in the code that I have NOT touched. I simply worked until all tests passed. I'm not sure if these cases need modifying or not. If they do, the tests need to be updated to cover it. I'd like some help from a more experienced coffeelint developer here.

### CODE REVIEW

**Comment by swang** [comment]
Hey thanks for doing this. Looks like the tests didn't pass because of the length limit, but that seems trivial to fix.

When did this property token get added? Would like to take a look at the CoffeeScript to see what changed. It looks like you got the tests passing regardless.

**Comment by lydell** [comment]
- https://github.com/jashkenas/coffeescript/commit/e42fc477478889bbdeb182f3dc7a2d9e9ea2803b
- https://github.com/jashkenas/coffeescript/commit/021d2e437630a60ef4ea53556c2f64cecb762b8c
- https://github.com/jashkenas/coffeescript/commit/585932cf5bda03d16cd772beb67c1f76f39fc09a
- https://github.com/jashkenas/coffeescript/commit/4d8cd032987f49b84484d194305ef7f71f3434cc
- https://github.com/jashkenas/coffeescript/commit/9a0babf5b1fe7a7e1b8d47653b84c6a7919dc5cf

`npm test` failed for me even before I started working on this, because of lint errors, but the test suite passed. I don't think I've introduced any new lint errors.

**Comment by swang** [comment]
Merged into a5babd23aa094132c0bdf97d47e639650aec72a5

**Comment by lydell** [comment]
Thanks! :+1:

**Pull request closed without merging**
