### PR TITLE
Fix #526

### LINKED ISSUE #526: browserify is unnecessary for dependency of production
please, move the browserify to `devDependencies`.

```bash
grep -r browserify src
# no require found
```

It also affect the installation time of [dependents of coffeelint](https://www.npmjs.com/browse/depended/coffeelint).

```bash
time npm install browserify
# npm install browserify  4.16s user 1.19s system 89% cpu 6.000 total
```

at OS 10.11 MacBook Pro (Retina, 15-inch, Mid 2014), 2.5 GHz Intel Core i7, 16 GB 1600 MHz DDR3

### PR DESCRIPTION
**Pull request by 59naga**

### CODE REVIEW

**Comment by AsaAyers** [comment]
hold on. I'm writing up an explanation why this is not the solutiuon.

**Comment by impinball** [comment]
@AsaAyers You still working on the explanation?

**Comment by AsaAyers** [comment]
That discussion happened over in #526

**Comment by impinball** [comment]
@AsaAyers Thanks

**Pull request closed without merging**
