### PR TITLE
cyclomatic_complexity: ignore nested functions

### LINKED ISSUE #530: cyclomatic_complexity
I would like to be able to configure this rule to only lint individual functions and not aggregate the complexity of nested functions.

```coffee
# Currently the cyclomatic complexity of x includes the cyclomatic complexity of y
# I would like a configuration to remove this 
x = ->
  #... 
  y = ->
  #...
```

Run into this in a few places.

* mocha tests
```coffee
describe 'object', ->
  beforeEach ->
  describe 'method1', ->
  describe 'method2', ->
```
* cucumber steps
```coffee
module.exports = ->
   @Given /a step/, ->
   @Then /a result/, -> 
```
* angular controller
```coffee
controller = ($scope) ->
  $scope.onSave = ->
  $scope.onClear = ->

module.exports = controller
```

Happy to implement if it would be accepted.

### PR DESCRIPTION
**Pull request by charlierudolph**
@swang 

resolves #530

### CODE REVIEW

**Comment by swang** [comment]
:100: can you just squash the two commits together?

**Comment by charlierudolph** [comment]
squashed

**Comment by charlierudolph** [comment]
Thanks! Any timeframe for the next release?

**Comment by swang** [comment]
Sorry for the delay, I just published v1.14.0 with these changes.

**Comment by charlierudolph** [comment]
Thanks!

**Pull request merged**
